export const SET_STOCKS = 'STOCKS/MUTATIONS/SET_STOCKS';
export const RND_STOCKS = 'STOCKS/MUTATIONS/RND_STOCKS';
export const BUY_STOCKS = 'STOCKS/ACTIONS/BUY_STOCKS';
export const INIT_STOCKS = 'STOCKS/ACTIONS/INIT_STOCKS';
export const RANDOMIZE_STOCKS = 'STOCKS/ACTIONS/RANDOMIZE_STOCKS';